---

- when:   dest|dirname != '' and dest|dirname != '~'
  raw:    mkdir -p {{dest|dirname}}
  environment:    ~

- synchronize:
    src:  '{{src}}'
    dest: '{{dest}}'

- when:
    -     src
    -     dest
    -     mode or owner or group
  script: >
    coreos-copy-chattr.sh
    {{dest or ""|quote}}
    {{mode or ""|quote}}
    {{owner or ""|quote}}
    {{group or ""|quote}}
