---

- when:   dest|dirname != '' and dest|dirname != '~'
  raw:    mkdir -p {{dest|dirname}}
  environment:    ~

- synchronize:
    src:  '{{src}}'
    dest: '{{dest}}'

- when:
    -     src != None and src != ""
    -     dest != None and dest != ""
    -     mode != None and mode != "" or owner != None and owner != ""  or group != None and group != "" 
  script: >
    coreos-copy-chattr.sh
    {{dest or ""|quote}}
    {{mode or ""|quote}}
    {{owner or ""|quote}}
    {{group or ""|quote}}
