---

- when:   dest|dirname != '' and dest|dirname != '~'
  raw:    mkdir -p {{dest|dirname}}
  environment:    ~

- synchronize:
    src:  '{{src}}'
    dest: '{{dest}}'

- when:
    -     (src)
    -     (dest)
    -     (mode) or (owner) or (group)
  raw:  |
          if [[ -n "{{mode|default('')}}" ]]; then
              chmod -R '{{mode}}'      {{dest|quote}}
          fi

          if [[ -n "{{owner|default('')}}" ]]; then
              chown -R '{{owner}}'     {{dest|quote}}
          fi

          if [[ -n "{{group|default('')}}" ]]; then
              chgrp -R '{{group}}'     {{dest|quote}}
          fi
